declare
ctn varchar2(100);
iterator number; -- Счетчик
amountTransactions number; -- Количество транзакций
tablePrefixDwh varchar2(10);
--workTables
executeOsaHistory varchar2(5000);
begin
ctn:='9030371112';
amountTransactions:=6;
tablePrefixDwh:='URL';
iterator:=0;

loop

--OSA_HISTORY
executeOsaHistory:='Insert into OSA_HISTORY_'||tablePrefixDwh||'
   (SUBSCRIBER_ID, START_CALL_DATE_TIME, END_CALL_DATE_TIME, ACTIVITY_TYPE, USAGE_AMOUNT, DESCRIPT, REASON_CODE, NEW_BALANCE_1, CHANGE_AMOUNT_1, NEW_BALANCE_2, CHANGE_AMOUNT_2, NEW_BALANCE_3, CHANGE_AMOUNT_3, NEW_BALANCE_4, CHANGE_AMOUNT_4, NEW_BALANCE_5, CHANGE_AMOUNT_5, NEW_BALANCE_6, CHANGE_AMOUNT_6, NEW_BALANCE_7, CHANGE_AMOUNT_7, NEW_BALANCE_8, CHANGE_AMOUNT_8, NEW_BALANCE_9, CHANGE_AMOUNT_9, NEW_BALANCE_10, CHANGE_AMOUNT_10, ACCOUNT_TYPE, APPLICATION_ID, SUBTYPE_ID, SLU_ID, UNIT_TYPE_ID, MERCHANT_ID, SESSION_DESC, CORRELATION_ID, CORRELATION_TYPE, ACCOUNT_ID, APPLICATION_DESC, OSA_ITEM, OSA_SUBTYPE, PARAM_CONFIRM_ID, PARAM_CONTRACT, QOS, SERVICE_PARAMETER_1, SERVICE_PARAMETER_2, SERVICE_PARAMETER_3, SERVICE_PARAMETER_4, SERVICE_PARAMETER_5, LOCATION_A3, LOCATION_A_TYPE, LOCATION_B, LOCATION_B_TYPE, IMSI, INFO_PARAMETER, CURRENCY, IDENTITY_ID, GROUP_ID, CHARGE_CODE, SPENDING_LIMIT1, SPENDING_LIMIT2, SPENDING_LIMIT3, SPENDING_LIMIT4, SPENDING_LIMIT5, SPENDING_LIMIT6, SPENDING_LIMIT7, SPENDING_LIMIT8, SPENDING_LIMIT9, SPENDING_LIMIT10, ORP_DATE, FUND_USAGE_TYPE, ISO_CODE, PREV_ISO_CODE, CONVERSION_RATE, CALL_ID, SLICE, BILLSYSTEM_CODE, LOCATION_A, BALANCES_INFO, ADDITIONAL_GROUP_INFO, SESSION_ID, RECORD_SOURCE)
 Values
   ('||ctn||',sysdate-7+'||iterator||'/(24*60), sysdate-7+'||iterator||'/(24*60),''unitBasedCharge'', 1000, 
    NULL, 400, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, 0, 224, 1806, 
    ''42'', 21, ''GPRS'', ''INT GPRS charging'', 12345, 
    2, 1, ''SGSN_IP_ADDRESS:193.152.100.38'',''''''Internet'''''', ''''''VOLUME_K'''''', 
    NULL, NULL, 86, -1, -1, 
    -1, -1, NULL, NULL, 2, 
    ''9030372222'', 2, ''240991420235429'', ''''''000000;000000;10000#GGSN6-5;3602306640;31728;1'''''', NULL, 
    NULL, NULL, 2490, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, sysdate-7+'||iterator||'/(24*60), 1, 
    ''RUR'', NULL, 1, 2029562997434, 122115318, 
    2, ''GPRS_BEELINE_ASIA'', ''[1~100~10~0]'', NULL, '||iterator||',1)';
execute immediate executeOsaHistory;
iterator:=iterator+1;
exit when iterator>amountTransactions;


end loop;
commit;
end;
